<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class FactoryMapper {
	/**
	 * @return MapperProperty
	 */
	static function createMapperProperty ():MapperProperty {
		return new MapperProperty();
	}

	/**
	 * @return MapperPropertyPrice
	 */
	static function createMapperPropertyPrice ():MapperPropertyPrice {
		return new MapperPropertyPrice();
	}

	/**
	 * @return MapperPropertyType
	 */
	static function createMapperPropertyType ():MapperPropertyType {
		return new MapperPropertyType();
	}

	/**
	 * @return MapperPlan
	 */
	static function createMapperPlan ():MapperPlan {
		return new MapperPlan();
	}

	/**
	 * @return MapperAgency
	 */
	static function createMapperAgency ():MapperAgency {
		return new MapperAgency();
	}

	/**
	 * @return MapperExtra
	 */
	static function createMapperExtra ():MapperExtra {
		return new MapperExtra();
	}

	/**
	 * @return MapperLocation
	 */
	static function createMapperLocation ():MapperLocation {
		return new MapperLocation();
	}

	/**
	 * @return MapperSeat
	 */
	static function createMapperSeat ():MapperSeat {
		return new MapperSeat();
	}

	/**
	 * @return MapperRequest
	 */
	static function createMapperRequest ():MapperRequest {
		return new MapperRequest();
	}

	/**
	 * @return MapperRating
	 */
	static function createMapperRating ():MapperRating {
		return new MapperRating();
	}

	/**
	 * @return MapperAccess
	 */
	static function createMapperAccess ():MapperAccess {
		return new MapperAccess();
	}

	/**
	 * @return MapperUser
	 */
	static function createMapperUser ():MapperUser {
		return new MapperUser();
	}

	/**
	 * @return MapperPropertyExtra
	 */
	static function createMapperPropertyExtra ():MapperPropertyExtra {
		return new MapperPropertyExtra();
	}

	/**
	 * @return MapperRol
	 */
	static function createMapperRol ():MapperRol {
		return new MapperRol();
	}

	/**
	 * @return MapperRolAccess
	 */
	static function createMapperRolAccess ():MapperRolAccess {
		return new MapperRolAccess();
	}
}