<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class FactoryMapper {
	/**
	 * @return MapperPropertyType
	 */
	static function createMapperPropertyType () {
		return new MapperPropertyType();
	}

	static function createMapperPlan () {
		return new MapperPlan();
	}
}