INSERT INTO location (lo_type, lo_name, lo_location_fk)
VALUES ('Pais', 'Venezuela', NULL);

INSERT INTO location (lo_type, lo_name, lo_location_fk)
VALUES ('Estado', 'Amazonas', 1),
       ('Estado', 'Anzoategui', 1),
       ('Estado', 'Apure', 1),
       ('Estado', 'Aragua', 1),
       ('Estado', 'Barinas', 1),
       ('Estado', 'Bolivar', 1),
       ('Estado', 'Carabobo', 1),
       ('Estado', 'Cojedes', 1),
       ('Estado', 'Delta Amacuro', 1),
       ('Estado', 'Falcon', 1),
       ('Estado', 'Guarico', 1),
       ('Estado', 'Lara', 1),
       ('Estado', 'Merida', 1),
       ('Estado', 'Miranda', 1),
       ('Estado', 'Monagas', 1),
       ('Estado', 'Nueva Esparta', 1),
       ('Estado', 'Portuguesa', 1),
       ('Estado', 'Sucre', 1),
       ('Estado', 'Tachira', 1),
       ('Estado', 'Trujillo', 1),
       ('Estado', 'Vargas', 1),
       ('Estado', 'Yaracuy', 1),
       ('Estado', 'Zulia', 1),
       ('Estado', 'Distrito Capital', 1);

INSERT INTO location (lo_type, lo_location_fk, lo_name)
VALUES ('Municipio', 2, 'Alto Orinoco'),
       ('Municipio', 2, 'Atabapo'),
       ('Municipio', 2, 'Atures'),
       ('Municipio', 2, 'Autana'),
       ('Municipio', 2, 'Manapiare'),
       ('Municipio', 2, 'Maroa'),
       ('Municipio', 2, 'Río Negro'),
       ('Municipio', 3, 'Anaco'),
       ('Municipio', 3, 'Aragua'),
       ('Municipio', 3, 'Bruzual'),
       ('Municipio', 3, 'Urbaneja'),
       ('Municipio', 3, 'Peñalver'),
       ('Municipio', 3, 'Carvajal'),
       ('Municipio', 3, 'McGgregor'),
       ('Municipio', 3, 'Guanta'),
       ('Municipio', 3, 'Independencia'),
       ('Municipio', 3, 'Monagas'),
       ('Municipio', 3, 'Sotillo'),
       ('Municipio', 3, 'Cajigal'),
       ('Municipio', 3, 'Libertad'),
       ('Municipio', 3, 'Miranda'),
       ('Municipio', 3, 'Freites'),
       ('Municipio', 3, 'Píritu'),
       ('Municipio', 3, 'Guanipa'),
       ('Municipio', 3, 'San Juan de Capistrano'),
       ('Municipio', 3, 'Santa Ana'),
       ('Municipio', 3, 'Bolivar'),
       ('Municipio', 3, 'Simón Rodríguez'),
       ('Municipio', 4, 'Achaguas'),
       ('Municipio', 4, 'Biruaca'),
       ('Municipio', 4, 'Muñóz'),
       ('Municipio', 4, 'Páez'),
       ('Municipio', 4, 'Pedro Camejo'),
       ('Municipio', 4, 'Rómulo Gallegos'),
       ('Municipio', 4, 'San Fernando'),
       ('Municipio', 5, 'Girardot'),
       ('Municipio', 5, 'Bolívar'),
       ('Municipio', 5, 'Camatagua'),
       ('Municipio', 5, 'Alcántara'),
       ('Municipio', 5, 'Lamas'),
       ('Municipio', 5, 'Ribas'),
       ('Municipio', 5, 'Revenga'),
       ('Municipio', 5, 'Libertador'),
       ('Municipio', 5, 'Iragorry'),
       ('Municipio', 5, 'Ocumare de la Costa de Oro'),
       ('Municipio', 5, 'San Casimiro'),
       ('Municipio', 5, 'San Sebastián'),
       ('Municipio', 5, 'Mariño'),
       ('Municipio', 5, 'Michelena'),
       ('Municipio', 5, 'Sucre'),
       ('Municipio', 5, 'Tovar'),
       ('Municipio', 5, 'Urdaneta'),
       ('Municipio', 5, 'Zamora'),
       ('Municipio', 6, 'Alberto Arvelo Torrealba'),
       ('Municipio', 6, 'Andrés Eloy Blanco'),
       ('Municipio', 6, 'Antonio José de Sucre'),
       ('Municipio', 6, 'Arismendi'),
       ('Municipio', 6, 'Barinas'),
       ('Municipio', 6, 'Bolívar'),
       ('Municipio', 6, 'Cruz Paredes'),
       ('Municipio', 6, 'Ezequiel Zamora'),
       ('Municipio', 6, 'Obispos'),
       ('Municipio', 6, 'Pedraza'),
       ('Municipio', 6, 'Rojas'),
       ('Municipio', 6, 'Sosa'),
       ('Municipio', 7, 'Caroní'),
       ('Municipio', 7, 'Cedeño'),
       ('Municipio', 7, 'El Callao'),
       ('Municipio', 7, 'Gran Sabana'),
       ('Municipio', 7, 'Heres'),
       ('Municipio', 7, 'Piar'),
       ('Municipio', 7, 'Angostura (Raúl Leoni)'),
       ('Municipio', 7, 'Roscio'),
       ('Municipio', 7, 'Sifontes'),
       ('Municipio', 7, 'Sucre'),
       ('Municipio', 7, 'Chien'),
       ('Municipio', 9, 'Bejuma'),
       ('Municipio', 9, 'Carlos Arvelo'),
       ('Municipio', 9, 'Diego Ibarra'),
       ('Municipio', 8, 'Guacara'),
       ('Municipio', 8, 'Mora'),
       ('Municipio', 8, 'Libertador'),
       ('Municipio', 8, 'Los Guayos'),
       ('Municipio', 8, 'Miranda'),
       ('Municipio', 8, 'Montalbán'),
       ('Municipio', 8, 'Naguanagua'),
       ('Municipio', 8, 'Puerto Cabello'),
       ('Municipio', 8, 'San Diego'),
       ('Municipio', 8, 'San Joaquín'),
       ('Municipio', 8, 'Valencia'),
       ('Municipio', 9, 'Anzoátegui'),
       ('Municipio', 9, 'Tinaquillo'),
       ('Municipio', 9, 'Girardot'),
       ('Municipio', 9, 'Lima Blanco'),
       ('Municipio', 9, 'Pao de San Juan Bautista'),
       ('Municipio', 9, 'Ricaurte'),
       ('Municipio', 9, 'Rómulo Gallegos'),
       ('Municipio', 9, 'San Carlos'),
       ('Municipio', 9, 'Tinaco'),
       ('Municipio', 10, 'Antonio Díaz'),
       ('Municipio', 10, 'Casacoima'),
       ('Municipio', 10, 'Pedernales'),
       ('Municipio', 10, 'Tucupita'),
       ('Municipio', 11, 'Acosta'),
       ('Municipio', 11, 'Bolívar'),
       ('Municipio', 11, 'Buchivacoa'),
       ('Municipio', 11, 'Manaure'),
       ('Municipio', 11, 'Carirubana'),
       ('Municipio', 11, 'Colina'),
       ('Municipio', 11, 'Dabajuro'),
       ('Municipio', 11, 'Democracia'),
       ('Municipio', 11, 'Falcón'),
       ('Municipio', 11, 'Federación'),
       ('Municipio', 11, 'Jacura'),
       ('Municipio', 11, 'Silva'),
       ('Municipio', 11, 'Los Taques'),
       ('Municipio', 11, 'Mauroa'),
       ('Municipio', 11, 'Miranda'),
       ('Municipio', 11, 'Iturriza'),
       ('Municipio', 11, 'Palmasola'),
       ('Municipio', 11, 'Petit'),
       ('Municipio', 11, 'Píritu'),
       ('Municipio', 11, 'San Francisco'),
       ('Municipio', 11, 'Sucre'),
       ('Municipio', 11, 'Tocópero'),
       ('Municipio', 11, 'Unión'),
       ('Municipio', 11, 'Urumaco'),
       ('Municipio', 11, 'Zamora'),
       ('Municipio', 12, 'Camaguán'),
       ('Municipio', 12, 'Chaguaramas'),
       ('Municipio', 12, 'El Socorro'),
       ('Municipio', 12, 'Ribas'),
       ('Municipio', 12, 'Monagas'),
       ('Municipio', 12, 'Roscio'),
       ('Municipio', 12, 'Julián Mellado'),
       ('Municipio', 12, 'Las Mercedes'),
       ('Municipio', 12, 'Leonardo Infante'),
       ('Municipio', 12, 'Zaraza'),
       ('Municipio', 12, 'Ortíz'),
       ('Municipio', 12, 'San Gerónimo de Guayabal'),
       ('Municipio', 12, 'San José de Guaribe'),
       ('Municipio', 12, 'Santa María de Ipire'),
       ('Municipio', 12, 'Francisco de Miranda'),
       ('Municipio', 13, 'Blanco'),
       ('Municipio', 13, 'Crespo'),
       ('Municipio', 13, 'Iribarren'),
       ('Municipio', 13, 'Jiménez'),
       ('Municipio', 13, 'Morán'),
       ('Municipio', 13, 'Palavecino'),
       ('Municipio', 13, 'Planas'),
       ('Municipio', 13, 'Torres'),
       ('Municipio', 13, 'Urdaneta'),
       ('Municipio', 14, 'Adriani'),
       ('Municipio', 14, 'Andrés Bello'),
       ('Municipio', 14, 'Pinto Salinas'),
       ('Municipio', 14, 'Aricagua'),
       ('Municipio', 14, 'Chacón'),
       ('Municipio', 14, 'Campo Elías'),
       ('Municipio', 14, 'Parra Olmedo'),
       ('Municipio', 14, 'Quintero'),
       ('Municipio', 14, 'Guaraque'),
       ('Municipio', 14, 'Salas'),
       ('Municipio', 14, 'Briceño'),
       ('Municipio', 14, 'Libertador'),
       ('Municipio', 14, 'Miranda'),
       ('Municipio', 14, 'Ramos de Lora'),
       ('Municipio', 14, 'Padre Noguera'),
       ('Municipio', 14, 'Pueblo Llano'),
       ('Municipio', 14, 'Rangel'),
       ('Municipio', 14, 'Dávila'),
       ('Municipio', 14, 'Marquina'),
       ('Municipio', 14, 'Sucre'),
       ('Municipio', 14, 'Tovar'),
       ('Municipio', 14, 'Febres Cordero'),
       ('Municipio', 14, 'Zea'),
       ('Municipio', 15, 'Acevedo'),
       ('Municipio', 15, 'Andrés Bello'),
       ('Municipio', 15, 'Baruta'),
       ('Municipio', 15, 'Brión'),
       ('Municipio', 15, 'Buroz'),
       ('Municipio', 15, 'Carrizal'),
       ('Municipio', 15, 'Chacao'),
       ('Municipio', 15, 'Cristóbal Rojas'),
       ('Municipio', 15, 'El Hatillo'),
       ('Municipio', 15, 'Guaicaipuro'),
       ('Municipio', 15, 'Independencia'),
       ('Municipio', 15, 'Lander'),
       ('Municipio', 15, 'Los Salias'),
       ('Municipio', 15, 'Páez'),
       ('Municipio', 15, 'Paz Castillo'),
       ('Municipio', 15, 'Pedro Gual'),
       ('Municipio', 15, 'Plaza'),
       ('Municipio', 15, 'Simón Bolívar'),
       ('Municipio', 15, 'Sucre'),
       ('Municipio', 15, 'Urdaneta'),
       ('Municipio', 15, 'Zamora'),
       ('Municipio', 16, 'Acosta'),
       ('Municipio', 16, 'Aguasay'),
       ('Municipio', 16, 'Bolívar'),
       ('Municipio', 16, 'Caripe'),
       ('Municipio', 16, 'Cedeño'),
       ('Municipio', 16, 'Zamora'),
       ('Municipio', 16, 'Libertador'),
       ('Municipio', 16, 'Maturín'),
       ('Municipio', 16, 'Piar'),
       ('Municipio', 16, 'Punceres'),
       ('Municipio', 16, 'Santa Bárbara'),
       ('Municipio', 16, 'Sotillo'),
       ('Municipio', 16, 'Uracoa'),
       ('Municipio', 17, 'Antolín del Campo'),
       ('Municipio', 17, 'Arismendi'),
       ('Municipio', 17, 'García'),
       ('Municipio', 17, 'Gómez'),
       ('Municipio', 17, 'Maneiro'),
       ('Municipio', 17, 'Marcano'),
       ('Municipio', 17, 'Mariño'),
       ('Municipio', 17, 'Macanao'),
       ('Municipio', 17, 'Tubores'),
       ('Municipio', 17, 'Villalba'),
       ('Municipio', 17, 'Díaz'),
       ('Municipio', 18, 'Agua Blanca'),
       ('Municipio', 18, 'Araure'),
       ('Municipio', 18, 'Esteller'),
       ('Municipio', 18, 'Guanare'),
       ('Municipio', 18, 'Guanarito'),
       ('Municipio', 18, 'Unda'),
       ('Municipio', 18, 'Ospino'),
       ('Municipio', 18, 'Páez'),
       ('Municipio', 18, 'Papelón'),
       ('Municipio', 18, 'San Genaro de Boconoíto'),
       ('Municipio', 18, 'San Rafael de Onoto'),
       ('Municipio', 18, 'Santa Rosalía'),
       ('Municipio', 18, 'Sucre'),
       ('Municipio', 18, 'Turén'),
       ('Municipio', 19, 'Blanco'),
       ('Municipio', 19, 'Mata'),
       ('Municipio', 19, 'Arismendi'),
       ('Municipio', 19, 'Benítez'),
       ('Municipio', 19, 'Bermúdez'),
       ('Municipio', 19, 'Bolívar'),
       ('Municipio', 19, 'Cajigal'),
       ('Municipio', 19, 'Cruz Salmerón Acosta'),
       ('Municipio', 19, 'Libertador'),
       ('Municipio', 19, 'Mariño'),
       ('Municipio', 19, 'Mejía'),
       ('Municipio', 19, 'Montes'),
       ('Municipio', 19, 'Ribero'),
       ('Municipio', 19, 'Sucre'),
       ('Municipio', 19, 'Valdéz'),
       ('Municipio', 20, 'Andrés Bello'),
       ('Municipio', 20, 'Rómulo Costa'),
       ('Municipio', 20, 'Ayacucho'),
       ('Municipio', 20, 'Bolívar'),
       ('Municipio', 20, 'Cárdenas'),
       ('Municipio', 20, 'Córdoba'),
       ('Municipio', 20, 'Fernández'),
       ('Municipio', 20, 'Miranda'),
       ('Municipio', 20, 'Hevia'),
       ('Municipio', 20, 'Guásimos'),
       ('Municipio', 20, 'Independencia'),
       ('Municipio', 20, 'Jáuregui'),
       ('Municipio', 20, 'Vargas'),
       ('Municipio', 20, 'Junín'),
       ('Municipio', 20, 'Libertad'),
       ('Municipio', 20, 'Libertador'),
       ('Municipio', 20, 'Lobatera'),
       ('Municipio', 20, 'Michelena'),
       ('Municipio', 20, 'Panamericano'),
       ('Municipio', 20, 'Ureña'),
       ('Municipio', 20, 'Urdaneta'),
       ('Municipio', 20, 'Maldonado'),
       ('Municipio', 20, 'San Cristóbal'),
       ('Municipio', 20, 'Seboruco'),
       ('Municipio', 20, 'Simón Rodríguez'),
       ('Municipio', 20, 'Sucre'),
       ('Municipio', 20, 'Torbes'),
       ('Municipio', 20, 'Uribante'),
       ('Municipio', 20, 'San Judas Tadeo'),
       ('Municipio', 21, 'Andrés Bello'),
       ('Municipio', 21, 'Boconó'),
       ('Municipio', 21, 'Bolívar'),
       ('Municipio', 21, 'Candelaria'),
       ('Municipio', 21, 'Carache'),
       ('Municipio', 21, 'Escuque'),
       ('Municipio', 21, 'José Felipe Márquez Cañizalez'),
       ('Municipio', 21, 'Juan Vicente Campos Elías'),
       ('Municipio', 21, 'La Ceiba'),
       ('Municipio', 21, 'Miranda'),
       ('Municipio', 21, 'Monte Carmelo'),
       ('Municipio', 21, 'Motatán'),
       ('Municipio', 21, 'Pampán'),
       ('Municipio', 21, 'Pampanito'),
       ('Municipio', 21, 'Rafael Rangel'),
       ('Municipio', 21, 'San Rafael de Carvajal'),
       ('Municipio', 21, 'Sucre'),
       ('Municipio', 21, 'Trujillo'),
       ('Municipio', 21, 'Urdaneta'),
       ('Municipio', 21, 'Valera'),
       ('Municipio', 22, 'Vargas'),
       ('Municipio', 23, 'Arístides Bastidas'),
       ('Municipio', 23, 'Bolívar'),
       ('Municipio', 23, 'Bruzual'),
       ('Municipio', 23, 'Cocorote'),
       ('Municipio', 23, 'Independencia'),
       ('Municipio', 23, 'José Antonio Páez'),
       ('Municipio', 23, 'La Trinidad'),
       ('Municipio', 23, 'Manuel Monge'),
       ('Municipio', 23, 'Nirgua'),
       ('Municipio', 23, 'Peña'),
       ('Municipio', 23, 'San Felipe'),
       ('Municipio', 23, 'Sucre'),
       ('Municipio', 23, 'Urachiche'),
       ('Municipio', 23, 'José Joaquín Veroes'),
       ('Municipio', 24, 'Almirante Padilla'),
       ('Municipio', 24, 'Baralt'),
       ('Municipio', 24, 'Cabimas'),
       ('Municipio', 24, 'Catatumbo'),
       ('Municipio', 24, 'Colón'),
       ('Municipio', 24, 'Francisco Javier Pulgar'),
       ('Municipio', 24, 'Páez'),
       ('Municipio', 24, 'Jesús Enrique Losada'),
       ('Municipio', 24, 'Jesús María Semprún'),
       ('Municipio', 24, 'La Cañada de Urdaneta'),
       ('Municipio', 24, 'Lagunillas'),
       ('Municipio', 24, 'Machiques de Perijá'),
       ('Municipio', 24, 'Mara'),
       ('Municipio', 24, 'Maracaibo'),
       ('Municipio', 24, 'Miranda'),
       ('Municipio', 24, 'Rosario de Perijá'),
       ('Municipio', 24, 'San Francisco'),
       ('Municipio', 24, 'Santa Rita'),
       ('Municipio', 24, 'Simón Bolívar'),
       ('Municipio', 24, 'Sucre'),
       ('Municipio', 24, 'Valmore Rodríguez'),
       ('Municipio', 25, 'Libertador');

INSERT INTO rol(ro_name)
VALUES ('Administrador');
INSERT INTO rol(ro_name)
VALUES ('Corredor');

INSERT INTO seat(se_name, se_rif, se_location_fk, se_agency_fk, se_user_created_fk, se_user_modified_fk)
VALUES ('C21 Los palos grandes', 'J-12306151', 20, 1, 1, 1);

INSERT INTO user(us_first_name, us_last_name, us_address, us_email,
                 us_password, us_active, us_seat_fk, us_rol_fk, us_plan_fk, us_location_fk,
                 us_user_created_fk, us_user_modified_fk)
VALUES ('Ramiro', 'Vargas', 'La candelaria', 'ramiroavch@gmail.com', '123456', 1, 1, 1, 1, 1, 1, 1);

INSERT INTO user(us_first_name, us_last_name, us_address, us_email,
                 us_password, us_active, us_seat_fk, us_rol_fk, us_plan_fk, us_location_fk,
                 us_user_created_fk, us_user_modified_fk)
VALUES ('Jose', 'Cedeno', 'Cumbres de Curumo', 'josejecr97@gmail.com', '123456', 1, 1, 1, 1, 1, 1, 1);

INSERT INTO property(pr_name, pr_area, pr_description, pr_status,
                     pr_floor, pr_type_fk, pr_user_created_fk, pr_location_fk,
                     pr_user_modified_fk)
VALUES ('Apartamento en los palos grandes', 125.23, 'bonito apartamento', 1, 0, 1, 1, 1, 1);
