<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
abstract class Entity {
	private $_id;

	/**
	 * @return int
	 */
	public function getId () {
		return $this->_id;
	}

	/**
	 * @param int $id Entity identification.
	 */
	public function setId ($id) {
		$this->_id = $id;
	}
}