<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
/**
 * @param string      $class
 * @param string|null $dir
 */
function autoload ($class, $dir = null) {
	$excludedDirectories = ['houston', 'vendor', 'Test', 'sql'];
	if (is_null($dir))
		$dir = __DIR__ . '/';
	foreach (scandir($dir) as $file) {
		$path = $dir . $file;
		// Is a directory and doesn't start with '.' (Ex: .idea)
		if (is_dir($path) && substr($file, 0, 1) !== '.' && !in_array($file, $excludedDirectories))
			autoload($class, $path . '/');
		// Is a valid php file
		if (substr($file, 0, 2) !== '._' && preg_match("/.php$/i", $file)) {
			// The name of the file match the class name
			if (str_replace('.php', '', $file) == $class || str_replace('.class.php', '', $file) == $class)
				/** @noinspection PhpIncludeInspection */
				require_once $path;
		}
	}
}

spl_autoload_register('autoload');