<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
abstract class Dto {
	public $id;
	public $userCreator;
	public $userModifier;
	public $dateCreated;
	public $dateModified;
	public $active;
	public $delete;
}