<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class FactoryDto {
	/**
	 * @param int    $id
	 * @param string $name
	 * @param bool   $active
	 *
	 * @return DtoPropertyType
	 */
	static function createDtoPropertyType (int $id, $name = '', $active = true):DtoPropertyType {
		return new DtoPropertyType($id, $name, $active);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param int    $price
	 * @param bool   $active
	 *
	 * @return DtoPlan
	 */
	static function createDtoPlan (int $id, $name = "", $price = 0, $active = true):DtoPlan {
		return new DtoPlan($id, $name, $price, $active);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param bool   $active
	 * @param null   $seats
	 *
	 * @return DtoAgency
	 */
	static function createDtoAgency (int $id, $name = "", $active = true, $seats = null):DtoAgency {
		return new DtoAgency($id, $name, $active, $seats);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param bool   $active
	 *
	 * @return DtoExtra
	 */
	static function createDtoExtra (int $id, $name = "", $active = true):DtoExtra {
		return new DtoExtra($id, $name, $active);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param string $type
	 *
	 * @return DtoLocation
	 */
	static function createDtoLocation (int $id, $name = "", $type = ""):DtoLocation {
		return new DtoLocation($id, $name, $type);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param string $rif
	 * @param bool   $active
	 *
	 * @return DtoSeat
	 */
	static function createDtoSeat (int $id, $name = "", $rif = "", $active = true):DtoSeat {
		return new DtoSeat($id, $name, $rif, $active);
	}

	/**
	 * @param int    $id
	 * @param string $date
	 * @param bool   $active
	 *
	 * @return DtoRequest
	 */
	static function createDtoRequest (int $id, $date = "", $active = true):DtoRequest {
		return new DtoRequest($id, $date, $active);
	}

	/**
	 * @param int                $id
	 * @param string             $name
	 * @param int                $area
	 * @param string             $description
	 * @param string             $publishDate
	 * @param int                $state
	 * @param int                $floor
	 * @param DtoExtra[]         $extras
	 * @param DtoRequest[]       $request
	 * @param DtoUser|null       $user
	 * @param DtoPropertyPrice[] $propertyPrice
	 *
	 * @return DtoProperty
	 */
	static function createDtoProperty (int $id, $name = "", $area = 0, $description = '', $publishDate = '',
		$state = 0, $floor = 0, $extras = [], $request = [], $user = null, $propertyPrice = []):DtoProperty {
		return new DtoProperty($id, $name, $area, $description, $publishDate, $state, $floor, $extras,
			$request, $user, $propertyPrice);
	}

	/**
	 * @param int    $id
	 * @param int    $price
	 * @param string $date
	 * @param bool   $final
	 * @param int    $propertyId
	 *
	 * @return DtoPropertyPrice
	 */
	static function createDtoPropertyPrice (int $id, $price = 0, $date = "", $final = false,
		int $propertyId = 0):DtoPropertyPrice {
		return new DtoPropertyPrice($id, $price, $date, $final, $propertyId);
	}

	/**
	 * @param int    $id
	 * @param float  $score
	 * @param string $message
	 * @param bool   $active
	 *
	 * @return DtoRating
	 */
	static function createDtoRating (int $id, $score = 0.0, $message = "", $active = true):DtoRating {
		return new DtoRating($id, $score, $message, $active);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param string $abbreviation
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return DtoAccess
	 */
	static function createDtoAccess (int $id, $name = "", $abbreviation = "", $dateCreated = "",
		$dateModified = ""):DtoAccess {
		return new DtoAccess($id, $name, $abbreviation, $dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param bool   $active
	 * @param bool   $delete
	 * @param        $userCreator
	 * @param        $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return DtoRol
	 */
	static function createDtoRol (int $id, string $name, bool $active, bool $delete, $userCreator, $userModifier,
		string $dateCreated = "", string $dateModified = ""):DtoRol {
		return new DtoRol($id, $name, $active, $delete, $userCreator, $userModifier, $dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $firstName
	 * @param string $lastName
	 * @param string $address
	 * @param string $email
	 * @param string $password
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param bool   $active
	 * @param bool   $blocked
	 * @param bool   $deleted
	 * @param int    $seat
	 * @param int    $rol
	 * @param int    $plan
	 * @param int    $location
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return DtoUser
	 */
	static function createDtoUser (int $id, string $firstName, string $lastName, string $address, string $email,
		string $password, int $userCreator, int $userModifier, bool $active, bool $blocked, bool $deleted, int $seat,
		int $rol, int $plan, int $location, string $dateCreated, string $dateModified):DtoUser {
		return new DtoUser($id, $firstName, $lastName, $address, $email, $password, $userCreator, $userModifier,
			$active, $blocked, $deleted, $seat, $rol, $plan, $location, $dateCreated, $dateModified);
	}
}