<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class ErrorResponse {
	public $errors;

	/**
	 * ErrorResponse constructor.
	 *
	 * @param array $errors
	 */
	public function __construct ($errors = []) {
		$this->errors = $errors;
	}
}