<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class Logger {
	private const PATH = __DIR__ . "/../systemLog.log";
	public const WARNING = "Warning";
	public const NOTICE = "Notice";
	public const ERROR = "Error";
	public const INFO = "Info";

	/**
	 * Print a message on log.
	 *
	 * @param string $message
	 * @param string $file
	 * @param string $level
	 */
	public static function log ($message, $file, $level) {
		$date = date('d/m/Y H:i:s u P');
		$line = "[{$date}] [{$file}] [{$level}] {$message}" . PHP_EOL;
		error_log($line, 3, self::PATH);
	}

	/**
	 * Print a error message on log.
	 *
	 * @param string $message
	 * @param string $file
	 */
	public static function error ($message, $file) {
		$date = date('d/m/Y H:i:s u P');
		$line = "[{$date}] [{$file}] [" . self::ERROR . "] {$message}" . PHP_EOL;
		error_log($line, 3, self::PATH);
	}

	/**
	 * Print a warning message on log.
	 *
	 * @param string $message
	 * @param string $file
	 */
	public static function warning ($message, $file) {
		$date = date('d/m/Y H:i:s u P');
		$line = "[{$date}] [{$file}] [" . self::WARNING . "] {$message}" . PHP_EOL;
		error_log($line, 3, self::PATH);
	}

	/**
	 * Print a notice message on log.
	 *
	 * @param string $message
	 * @param string $file
	 */
	public static function notice ($message, $file) {
		$date = date('d/m/Y H:i:s u P');
		$line = "[{$date}] [{$file}] [" . self::NOTICE . "] {$message}" . PHP_EOL;
		error_log($line, 3, self::PATH);
	}

	/**
	 * Print a info message on log.
	 *
	 * @param string $message
	 * @param string $file
	 */
	public static function info ($message, $file) {
		$date = date('d/m/Y H:i:s u P');
		$line = "[{$date}] [{$file}] [" . self::INFO . "] {$message}" . PHP_EOL;
		error_log($line, 3, self::PATH);
	}

	/**
	 * Print an exception error message on log.
	 *
	 * @param Exception $exception
	 * @param string    $level
	 */
	public static function exception ($exception, $level) {
		$date = date('d/m/Y H:i:s u P');
		$line = "[{$date}] [{$exception->getFile()}] [{$level}] on line: " . $exception->getLine() . " " .
			$exception->getMessage() . PHP_EOL;
		error_log($line, 3, self::PATH);
	}
}