<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class Tools {
	/**
	 * Headers Control
	 */
	public static function headers () {
		header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE");
		header('Content-Type: application/json');
		switch ($_SERVER['REQUEST_METHOD']) {
			case 'GET':
				header("Access-Control-Allow-Headers: access");
				header("Access-Control-Allow-Origin: *");
				header("Access-Control-Allow-Credentials: true");
				break;
			case 'POST' | 'PUT' | 'DELETE':
				header("Access-Control-Allow-Origin: *");
				header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");
				header("Access-Control-Max-Age: 3600");
				header("Content-Type: application/json; charset=UTF-8");
				break;
		}
	}

	/**
	 * Redirect to given page.
	 *
	 * @param string $page
	 *
	 * @return string
	 */
	public static function redirect ($page = "") {
		header("location: " . Environment::baseURL() . "/" . $page);
		exit;
	}

	/**
	 * Get current IP address
	 * @return string
	 */
	public static function getIP () {
		if (!empty($_SERVER['HTTP_CLIENT_IP']))
			$ip = $_SERVER['HTTP_CLIENT_IP'];
		elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))
			$ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
		else
			$ip = $_SERVER['REMOTE_ADDR'];

		return $ip;
	}
}