<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class Tools {
	/**
	 * Headers Control
	 */
	public static function headers () {
		header('Content-Type: application/json');
		header('Access-Control-Allow-Origin: *');
		header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method");
		header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
		header("Allow: GET, POST, OPTIONS, PUT, DELETE");
		if ($_SERVER['REQUEST_METHOD'] == "OPTIONS")
			die;
	}

	/**
	 * Redirect to given page.
	 *
	 * @param string $page
	 *
	 * @return string
	 */
	public static function redirect ($page = "") {
		header("location: " . Environment::baseURL() . "/" . $page);
		exit;
	}

	/**
	 * Get current IP address
	 * @return string
	 */
	public static function getIP () {
		if (!empty($_SERVER['HTTP_CLIENT_IP']))
			$ip = $_SERVER['HTTP_CLIENT_IP'];
		elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))
			$ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
		else
			$ip = $_SERVER['REMOTE_ADDR'];

		return $ip;
	}

	/**
	 * @return object
	 */
	static function getObject () {
		return (object) $_GET;
	}

	/**
	 * @return object
	 */
	static function postObject () {
		return (object) $_POST;
	}

	/**
	 * @param $date
	 *
	 * @return string
	 */
	static function formatDate ($date) {
		try {
			$date = new DateTime($date);

			return $date->format('d-m-Y h:iA');
		}
		catch (Exception $exception) {
			Logger::exception($exception, Logger::WARNING);

			return $date = "";
		}
	}

	/**
	 * @param string $string
	 *
	 * @return string
	 */
	static function encryptSha256 (string $string) {
		return hash('sha256', $string);
	}

	/**
	 * @param string $string
	 *
	 * @return string
	 */
	static function siteEncrypt ($string) {
		$key = Environment::siteKey();
		for ($i = 0; $i < strlen($key); $i++)
			$string = str_replace($key[$i], $i, $string);

		return $string;
	}

	/**
	 * @param int $responseCode
	 */
	public static function setResponse ($responseCode = 200) {
		http_response_code($responseCode);
	}

	/**
	 * @param Dto $dto
	 * @param int $creator
	 * @param int $modifier
	 *
	 * @throws DatabaseConnectionException
	 * @throws MultipleUserException
	 * @throws UserNotFoundException
	 */
	static function setUserToDto (Dto $dto, int $creator, int $modifier):void {
		$dao = FactoryDao::createDaoUser();
		$mapperUser = FactoryMapper::createMapperUser();
		$dto->userCreator = $mapperUser->fromEntityToDto($dao->getUserById($creator));
		$dto->userModifier = $mapperUser->fromEntityToDto($dao->getUserById($modifier));
		unset($dto->userCreator->userCreator);
		unset($dto->userCreator->userModifier);
		unset($dto->userModifier->userCreator);
		unset($dto->userModifier->userModifier);
	}
}