<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class Tools {
	/**
	 * Headers Control
	 */
	public static function headers () {
		header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");
		header('Content-Type: application/json');
		header("Access-Control-Allow-Origin: *");
		switch ($_SERVER['REQUEST_METHOD']) {
			case 'GET':
				header("Access-Control-Allow-Headers: access");
				header("Access-Control-Allow-Credentials: true");
				break;
			case 'POST' | 'PUT' | 'DELETE':
				header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");
				header("Access-Control-Max-Age: 3600");
				break;
		}
	}

	/**
	 * Redirect to given page.
	 *
	 * @param string $page
	 *
	 * @return string
	 */
	public static function redirect ($page = "") {
		header("location: " . Environment::baseURL() . "/" . $page);
		exit;
	}

	/**
	 * Get current IP address
	 * @return string
	 */
	public static function getIP () {
		if (!empty($_SERVER['HTTP_CLIENT_IP']))
			$ip = $_SERVER['HTTP_CLIENT_IP'];
		elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))
			$ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
		else
			$ip = $_SERVER['REMOTE_ADDR'];

		return $ip;
	}

	/**
	 * @return object
	 */
	static function getObject () {
		return (object) $_GET;
	}

	/**
	 * @param $date
	 *
	 * @return string
	 */
	static function formatDate ($date) {
		try {
			$date = new DateTime($date);

			return $date->format('d-m-Y h:iA');
		}
		catch (Exception $exception) {
			Logger::exception($exception, Logger::WARNING);

			return $date = "";
		}
	}

	/**
	 * @param string $string
	 *
	 * @return string
	 */
	static function encryptSha256(string $string){
		return hash('sha256', $string);
	}

	/**
	 * @param string $string
	 *
	 * @return string
	 */
	static function siteEncrypt ($string) {
		$key = Environment::siteKey();
		for ($i = 0; $i < strlen($key); $i++)
			$string = str_replace($key[$i], $i, $string);
		return $string;
	}

	/**
	 * @param int $responseCode
	 */
	public static function setResponse ($responseCode = 200) {
		http_response_code($responseCode);
	}
}