<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class Values {
	private const VALUES = array (
		'ACTIVE' => array ('text' => 'Active', 'value' => 1),
		'INACTIVE' => array ('text' => 'Inactive', 'value' => 0)
	);

	/**
	 * Get text value of a field
	 *
	 * @param string $key
	 *
	 * @return mixed|null
	 */
	public static function getText ($key) {
		return isset(self::VALUES[$key]) ? self::VALUES[$key]['text'] : null;
	}

	/**
	 * Get value of a field
	 *
	 * @param string $key
	 *
	 * @return mixed|null
	 */
	public static function getValue ($key) {
		return isset(self::VALUES[$key]) ? self::VALUES[$key]['value'] : null;
	}
}