<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class FactoryDao {
	/**
	 * @return DaoPropertyType
	 */
	static function createDaoPropertyType ():DaoPropertyType {
		return new DaoPropertyType();
	}

	/**
	 * @return DaoPlan
	 */
	static function createDaoPlan ():DaoPlan {
		return new DaoPlan();
	}

	/**
	 * @return DaoAgency
	 */
	static function createDaoAgency ():DaoAgency {
		return new DaoAgency();
	}

	/**
	 * @return DaoExtra
	 */
	static function createDaoExtra ():DaoExtra {
		return new DaoExtra();
	}

	/**
	 * @return DaoLocation
	 */
	static function createDaoLocation ():DaoLocation {
		return new DaoLocation();
	}

	/**
	 * @return DaoSeat
	 */
	static function createDaoSeat ():DaoSeat {
		return new DaoSeat();
	}

	/**
	 * @return DaoRequest
	 */
	static function createDaoRequest ():DaoRequest {
		return new DaoRequest();
	}

	/**
	 * @return DaoPropertyPrice
	 */
	static function createDaoPropertyPrice ():DaoPropertyPrice {
		return new DaoPropertyPrice();
	}

	/**
	 * @return DaoProperty
	 */
	static function createDaoProperty ():DaoProperty {
		return new DaoProperty();
	}

	/**
	 * @return DaoRating
	 */
	static function createDaoRating ():DaoRating {
		return new DaoRating();
	}
}