<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class FactoryDao {
    /**
     * @return DaoPropertyType
     */
    public static function createDaoPropertyType() {
        return new DaoPropertyType();
    }
}