<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
require_once __DIR__ . "/../autoload.php";
class Environment {
	//	Site settings
	private const SITE_KEY = "";
	//	Database connections settings
	private const HOST = "buscamatch.db.9357332.c65.hostedresource.net";
	private const DATABASE = "buscamatch";
	private const USERNAME = "buscamatch";
	private const PASSWORD = "best!M4tch";

	/**
	 * @return PDO
	 */
	public static function database ():PDO {
		try {
			$PDO = new PDO("mysql:host=" . self::HOST . ";dbname=" . self::DATABASE, self::USERNAME,
				self::PASSWORD);
			$PDO->exec("set names utf8");
			$PDO->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

			return $PDO;
		}
		catch (Exception $exception) {
			Logger::exception($exception, Logger::ERROR);
		}

		return null;
	}

	/**
	 * @return string
	 */
	public static function baseURL ():string {
		return self::BASE_URL;
	}

	/**
	 * @return string
	 */
	public static function siteKey ():string {
		return self::SITE_KEY;
	}
}