DROP TABLE favourite;
DROP TABLE subscription_detail;
DROP TABLE subscription;
DROP TABLE origin;
DROP TABLE property_extra;
DROP TABLE extra;
DROP TABLE property_price;
DROP TABLE request;
DROP TABLE property;
DROP TABLE property_type;
DROP TABLE rating;
DROP TABLE rol_access;
DROP TABLE access;
ALTER TABLE user DROP CONSTRAINT user_ibfk_1;
DROP TABLE seat;
DROP TABLE agency;
ALTER TABLE user DROP CONSTRAINT user_ibfk_3;
ALTER TABLE user DROP CONSTRAINT user_ibfk_2;
ALTER TABLE user DROP CONSTRAINT user_ibfk_4;
DROP TABLE plan;
DROP TABLE location;
DROP TABLE rol;
DROP TABLE user;