ALTER TABLE user DROP COLUMN us_location_fk;
ALTER TABLE user DROP COLUMN us_seat_fk;
ALTER TABLE user DROP COLUMN us_plan_fk;
ALTER TABLE user DROP COLUMN us_rol_fk;
DROP TABLE favorite;
DROP TABLE subscription_detail;
DROP TABLE subscription;
DROP TABLE origin;
DROP TABLE property_extra;
DROP TABLE extra;
DROP TABLE property_price;
DROP TABLE request;
DROP TABLE property;
DROP TABLE property_type;
DROP TABLE rating;
DROP TABLE rol_access;
DROP TABLE access;
DROP TABLE seat;
DROP TABLE agency;
DROP TABLE plan;
DROP TABLE location;
DROP TABLE rol;
DROP TABLE user;