<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
abstract class Command {
	private $_data = null;
	protected $_dao = null;

	public abstract function execute ():void;

	public abstract function return ();

	/**
	 * @return mixed
	 */
	protected function getData () {
		return $this->_data;
	}

	/**
	 * @param mixed $data
	 */
	protected function setData ($data):void {
		$this->_data = $data;
	}

	/**
	 * @return Dao
	 */
	public function getDao () {
		return $this->_dao;
	}

	/**
	 * @param Dao $dao
	 */
	public function setDao ($dao):void {
		$this->_dao = $dao;
	}
}