<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
require_once __DIR__ . "/../../autoload.php";
class FactoryCommand {
	/**
	 * @return GetAllPropertyTypeCommand
	 */
	static function createGetAllPropertyTypeCommand ():GetAllPropertyTypeCommand {
		return new GetAllPropertyTypeCommand();
	}

	/**
	 * @param $id
	 *
	 * @return GetPropertyTypeByIdCommand
	 */
	static function createGetPropertyTypeByIdCommand ($id):GetPropertyTypeByIdCommand {
		return new GetPropertyTypeByIdCommand($id);
	}

	/**
	 * @return GetAllPlanCommand
	 */
	static function createGetAllPlanCommand () {
		return new GetAllPlanCommand();
	}

	/**
	 * @param $id
	 *
	 * @return GetPlanByIdCommand
	 */
	static function createGetPlanByIdCommand ($id) {
		return new GetPlanByIdCommand($id);
	}

	static function createGetAllAgenciesCommand () {
		return new GetAllAgenciesCommand();
	}

	static function createGetAgenciesById ($id) {
		return new GetAgenciesByIdCommand($id);
	}
}