<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
require_once __DIR__ . "/../../autoload.php";
class FactoryEntity {
	/**
	 * @param        $id
	 * @param string $name
	 *
	 * @return PropertyType
	 */
	static function createPropertyType ($id, $name = ''):PropertyType {
		return new PropertyType($id, $name);
	}
}