<?php
/**
 * Generated by Houston
 * Date: 19-Nov-19
 * Time: 12:29 PM
 */
class FactoryEntity {
	/**
	 * @param int    $id
	 * @param string $name
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return PropertyType
	 */
	static function createPropertyType (int $id, string $name = "", int $userCreator = 1, int $userModifier = 1,
		$active = true, $delete = false, string $dateCreated = "", string $dateModified = ""):PropertyType {
		return new PropertyType($id, $name, $active, $delete, $userCreator, $userModifier, $dateCreated,
			$dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param float  $price
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return Plan
	 */
	static function createPlan (int $id, string $name = " ", float $price = 0.0, int $userCreator = 0,
		int $userModifier = 0, bool $active = true, bool $delete = false, string $dateCreated = "",
		string $dateModified = ""):Plan {
		return new Plan($id, $name, $price, $active, $delete, $userCreator, $userModifier, $dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return Agency
	 */
	static function createAgency (int $id, $name = "", int $userCreator = 0, int $userModifier = 0,
		string $dateCreated = "", string $dateModified = "", $active = true, $delete = false):Agency {
		return new Agency($id, $name, $active, $delete, $userCreator, $userModifier, $dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 * @param float  $value
	 * @param string $icon
	 *
	 * @return Extra
	 */
	static function createExtra (int $id, $name = "", string $icon = "", $active = true, $delete = false,
		int $userCreator = 0, int $userModifier = 0,
		string $dateCreated = "", string $dateModified = "",
		float $value = 0):Extra {
		return new Extra($id, $name, $icon, $active, $delete, $userCreator, $userModifier, $dateCreated,
			$dateModified, $value);
	}

	/**
	 * @param        $id
	 * @param string $name
	 * @param string $type
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return Location
	 */
	static function createLocation ($id, $name = "", $type = "", $active = true, $delete = false, int $userCreator = 0,
		int $userModifier = 0, string $dateCreated = "", string $dateModified = ""):Location {
		return new Location($id, $name, $type, $active, $delete, $userCreator, $userModifier, $dateCreated,
			$dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param string $rif
	 * @param int    $location
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return Seat
	 */
	static function createSeat (int $id, $name = "", $rif = "", $location = 0, $agency = 0, $active = true,
		$delete = false, int $userCreator = 0,
		int $userModifier = 0, string $dateCreated = "", string $dateModified = ""):Seat {
		return new Seat($id, $name, $rif, $location, $agency, $active, $delete, $userCreator, $userModifier,
			$dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $property
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return Request
	 */
	static function createRequest (int $id, int $property = 0, $active = true, $delete = false, int $userCreator = 0,
		int $userModifier = 0, string $dateCreated = "", string $dateModified = ""):Request {
		return new Request($id, $property, $active, $delete, $userCreator, $userModifier, $dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param int    $price
	 * @param bool   $final
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 * @param int    $propertyId
	 *
	 * @return PropertyPrice
	 */
	static function createPropertyPrice (int $id, $price = 0, int $propertyId = 0, $final = false, $active = true,
		$delete = false, int $userCreator = 0, int $userModifier = 0, string $dateCreated = "",
		string $dateModified = ""):PropertyPrice {
		return new PropertyPrice($id, $price, $final, $propertyId, $active, $delete, $userCreator, $userModifier,
			$dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param float  $area
	 * @param string $description
	 * @param int    $state
	 * @param int    $floor
	 * @param int    $type
	 * @param int    $location
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return Property
	 */
	static function createProperty (int $id, $name = "", $area = 0.0, $description = "", $state = 0, $floor = 0,
		$type = 0, $location = 0, $active = true, $delete = false, $userCreator = 0, $userModifier = 0,
		string $dateCreated = "", string $dateModified = ""):Property {
		return new Property($id, $name, $area, $description, $state, $floor, $type, $location, $active, $delete,
			$userCreator, $userModifier, $dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $firstName
	 * @param string $lastName
	 * @param string $address
	 * @param string $email
	 * @param string $password
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param bool   $active
	 * @param bool   $blocked
	 * @param bool   $deleted
	 * @param int    $seat
	 * @param int    $rol
	 * @param int    $plan
	 * @param int    $location
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return User
	 */
	static function createUser (int $id,
		string $firstName = "",
		string $lastName = "",
		string $address = "",
		string $email = "",
		string $password = "",
		int $userCreator = 1,
		int $userModifier = 1,
		bool $active = true,
		bool $blocked = false,
		bool $deleted = false,
		int $seat = 1,
		int $rol = 1,
		int $plan = 1,
		int $location = 1,
		string $dateCreated = "",
		string $dateModified = ""):User {
		return new User($id, $firstName, $lastName, $address, $email, $password, $userCreator, $userModifier, $active,
			$blocked, $deleted, $seat, $rol, $plan, $location, $dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param float  $score
	 * @param string $message
	 * @param int    $user
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return Rating
	 */
	static function createRating (int $id, $score = 0.0, $message = "", $user = 0, $active = true, $delete = false,
		int $userCreator = 0, int $userModifier = 0, string $dateCreated = "", string $dateModified = ""):Rating {
		return new Rating($id, $score, $message, $user, $active, $delete, $userCreator, $userModifier, $dateCreated,
			$dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param string $abbreviation
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return Access
	 */
	static function createAccess (int $id, $name = "", $abbreviation = "", $active = true, $delete = false,
		int $userCreator = 1, int $userModifier = 1, $dateCreated = "", $dateModified = ""):Access {
		return new Access($id, $name, $abbreviation, $active, $delete, $userCreator, $userModifier, $dateCreated,
			$dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return Rol
	 */
	static function createRol (int $id, $name = "", $active = true, $delete = false, $userCreator = 0,
		$userModifier = 0,
		$dateCreated = "", $dateModified = ""):Rol {
		return new Rol($id, $name, $active, $delete, $userCreator, $userModifier, $dateCreated, $dateModified);
	}

	/**
	 * @param int    $id
	 * @param string $name
	 * @param string $privateKey
	 * @param string $publicKey
	 * @param bool   $active
	 *
	 * @return Origin
	 */
	static function createOrigin (int $id, string $name = '', string $privateKey = '', string $publicKey = '',
		bool $active = true):Origin {
		return new Origin($id, $name, $privateKey, $publicKey, $active);
	}

	/**
	 * @param int    $id
	 * @param int    $value
	 * @param int    $propertyId
	 * @param int    $extraId
	 * @param bool   $active
	 * @param bool   $delete
	 * @param int    $userCreator
	 * @param int    $userModifier
	 * @param string $dateCreated
	 * @param string $dateModified
	 *
	 * @return PropertyExtra
	 */
	static function createPropertyExtra (int $id, int $value = 0, int $propertyId = 0, int $extraId = 0,
		bool $active = true,
		bool $delete = false, int $userCreator = 0, int $userModifier = 0, string $dateCreated = "",
		string $dateModified = ""):PropertyExtra {
		return new PropertyExtra($id, $value, $propertyId, $extraId, $active, $delete, $userCreator, $userModifier,
			$dateCreated,
			$dateModified);
	}
}